read_strict_csv <- function(path, ...) {
  data <- readr::read_csv(path, show_col_types = FALSE, ...)
  if (nrow(readr::problems(data)) > 0) stop("Parsing problems in ", path)
  data
}

# The Cor and Sood release scores each answer 1 (correct), 0 (incorrect), or
# missing (don't know or no answer); rows are participants in both waves.
answer_state <- function(x) {
  dplyr::case_when(x == 1 ~ "correct", x == 0 ~ "incorrect", is.na(x) ~ "dk") |>
    factor(levels = c("correct", "dk", "incorrect"))
}

read_tab <- \(name) readr::read_csv(file.path(TABLE_DIR, name), show_col_types = FALSE)

pct <- \(x, digits = 0) paste0(formatC(100 * x, format = "f", digits = digits), "\\%")
pts <- \(x) formatC(100 * x, format = "f", digits = 0)
count <- \(x) prettyNum(x, big.mark = ",")

digit_names <- c("Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine")

# Macro names may contain letters only.
macro_name <- function(x) {
  x |>
    stringr::str_replace_all("[0-9]", \(d) digit_names[as.integer(d) + 1]) |>
    stringr::str_replace_all("[^A-Za-z]", "")
}

write_macros <- function(values, path) {
  lines <- paste0("\\newcommand{\\", macro_name(names(values)), "}{", values, "}")
  if (anyDuplicated(macro_name(names(values)))) stop("Duplicate macro names")
  writeLines(c("% Generated by scripts/04_tables.R; do not edit.", lines), path)
}

latex_escape <- function(x) {
  x |>
    stringr::str_replace_all("\\\\", "\\\\textbackslash{}") |>
    stringr::str_replace_all("([&%$#_{}])", "\\\\\\1") |>
    stringr::str_replace_all("\"([^\"]*)\"", "``\\1''")
}

# A longtable carries its own caption and label so it can break across pages.
write_table <- function(data, path, align, header, caption = NULL, label = NULL) {
  body <- apply(data, 1, \(row) paste0(paste(row, collapse = " & "), " \\\\"))
  head <- paste0(paste(header, collapse = " & "), " \\\\")
  if (is.null(caption)) {
    lines <- c(
      paste0("\\begin{tabular}{", align, "}"),
      "\\toprule", head, "\\midrule", body, "\\bottomrule",
      "\\end{tabular}"
    )
  } else {
    lines <- c(
      paste0("\\begin{longtable}{", align, "}"),
      paste0("\\caption{", caption, "}\\label{", label, "}\\\\"),
      "\\toprule", head, "\\midrule", "\\endfirsthead",
      "\\toprule", head, "\\midrule", "\\endhead",
      "\\bottomrule", "\\endlastfoot",
      body,
      "\\end{longtable}"
    )
  }
  lines <- c(
    "\\begingroup",
    paste0("\\", TABLE_STYLE$size),
    paste0("\\setlength{\\tabcolsep}{", TABLE_STYLE$column_sep, "}"),
    paste0("\\renewcommand{\\arraystretch}{", TABLE_STYLE$row_spacing, "}"),
    lines,
    "\\endgroup"
  )
  writeLines(lines, path)
}

save_figure <- function(plot, name) {
  size <- FIGURE_SIZES[[name]]
  path <- file.path(FIGURE_DIR, name)
  ggplot2::ggsave(paste0(path, ".pdf"), plot, width = size[["width"]], height = size[["height"]])
  ggplot2::ggsave(
    paste0(path, ".png"), plot,
    width = size[["width"]], height = size[["height"]], dpi = FIGURE_DPI
  )
}

wilson <- function(successes, n, z = qnorm(0.975)) {
  p <- successes / n
  centre <- (p + z^2 / (2 * n)) / (1 + z^2 / n)
  half <- z * sqrt(p * (1 - p) / n + z^2 / (4 * n^2)) / (1 + z^2 / n)
  tibble::tibble(estimate = p, lower = centre - half, upper = centre + half)
}

# Point estimates and 95% intervals look the same in every figure.
geom_estimate <- function(...) {
  ggplot2::geom_pointrange(
    ggplot2::aes(xmin = lower, xmax = upper),
    shape = 16, size = 0.3, linewidth = 0.45, ...
  )
}

geom_zero <- function() ggplot2::geom_vline(xintercept = 0, colour = COLORS[["reference"]], linewidth = 0.3)
